application: webhoudini
version: 2
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /flat_web
  static_dir: flat_web/
- url: /.*
  script: main.py

libraries:
- name: webapp2
  version: "2.5.1"
